# Requires to build before, locally, this image (not provided on pramsey dockerhub repo. It's only used from transitiory purpose anyway
FROM pramsey/pg_tileserv:latest-alpine

COPY ./config /config/
COPY --chown=1001 ./wait-for-db.sh /
